### ISSUE TITLE
Favicon display

### ISSUE THREAD

**Issue by matthewolckers** [EAAMO/conference2024#1]
The current favicon has a white square background around it, which doesn't look very good. 

It should probably have a transparent background but also needs to display well on dark backgrounds. 

<img width="300" alt="image" src="https://github.com/EAAMO/conference24/assets/10639770/8e21b47d-fc64-472d-acd8-99a7475e4ccf">

**Comment by sandroradovanovic** [comment]
Done with [ed6ad93](https://github.com/EAAMO/conference24/commit/ed6ad93e5bee0755e52379f056c8778aff1bfc86)

**Comment by sandroradovanovic** [comment]
Done with [ed6ad93](https://github.com/EAAMO/conference24/commit/ed6ad93e5bee0755e52379f056c8778aff1bfc86)
