### ISSUE TITLE
Conference homepage

### ISSUE THREAD

**Issue by matthewolckers** [EAAMO/conference2024#2]
The current conference homepage is too bland. We need a conference homepage that 
- communicates essential information,
- looks good,
- links to important calls to action.

We can include a custom homepage with the Congo theme. See docs [here](https://jpanther.github.io/congo/docs/homepage-layout/#custom-layout).  

![Screenshot of current homepage](https://github.com/EAAMO/conference24/assets/10639770/c289afa0-26b1-46fe-b311-a884c384fbbd)

**Comment by matthewolckers** [comment]
Sam Wells had this comment on the current version of the homepage:
> Would be great to make the hero section at the top of the site follow a common web standard or a key piece of text that describes what this website is about. An example here https://www.wemanageprop.com/ that I did with this site - so that it is clear instantly what EAAMO 2024 is, then we can go into detail with the paragraph of information further down. I'd pair that opening statement/piece of text with some other part of the imagery from the brand guide - perhaps a pattern, or image to help establish the brand right up front.

**Comment by sandroradovanovic** [comment]
In an attempt to be helpful, I would suggest testing `profile` page setup (`config/_default/params.toml` set `homepage.layout = "profile"`). 

This setup uses the information provided in `config/_default/languages.en.toml` file. More specifically, `params.author` things like name, image, headline, bio, and all the links we provide. They are on the top of the screen and text provided in `content/_index.md` is beneath it. It looks OK (it will look really good with minor tweaks). Name can show the full name of the conference, image the logo, headline the dates, and links can lead to Twitter, main mail, YouTube, etc.

With this setup, we probably should remove the logo on the top left side in the menu and create a menu item Home that will lead to the home page.

**Comment by matthewolckers** [comment]
@sandroradovanovic shared the idea below on the content that may be important to go on the homepage.

![Conference_home_page_idea](https://github.com/EAAMO/conference24/assets/10639770/1a194e1f-3c4a-4c4b-93f8-c12dc15c62f3)

**Comment by matthewolckers** [comment]
One way that may be easier to build the homepage is:
1. Design the homepage in Carrd using one of the landing theme templates: https://carrd.co/build#landing
2. Download the HTML and CSS of the landing page we design (you can do this with a Pro subscription and I already have a Pro subscription)
3. Import this single page into the conference24 website

**Comment by matthewolckers** [comment]
The conference is being held in the city of [San Luis Potosí](https://en.wikipedia.org/wiki/San_Luis_Potos%C3%AD_(city)).

I found photos by a local photographer that we may be able to use for the banner photo. See [this photo](https://www.flickr.com/photos/lucynieto/46980880322/in/album-72157601809310223/) for example. There are lots more in the photographer's album on the city.

**Comment by matthewolckers** [comment]
The Carrd homepage didn't look very good so resorted to a very simple clean homepage. Might improve it in the future with the help of the web designer but it's fine for now.
