### ISSUE TITLE
Change text colour to brand dark blue

### ISSUE THREAD

**Issue by matthewolckers** [EAAMO/conference2024#3]
Change text colour to dark blue. Dark blue is: 

> Hex #1F2A60
> R 31 G 42 B 96
> C 100 M 94 Y 33 K 23

We should also define the other theme colours in a consistent way. 

The colours in the Congo theme are complex because the [theme uses Tailwind colour palettes](https://jpanther.github.io/congo/docs/advanced-customisation/#colour-schemes). 

I tried to use brand colors and [uicolors.app/create](https://uicolors.app/create) to define gradients, but then that messed with the dark version of the site. One solution is we could turn off the dark version but that seems like a last resort. 

Sandro did find what some of the main colours correspond to, but we still need to change the rest of the colour range. 
```
  --color-neutral-700: 31, 42, 96; /* TEXT */
  --color-neutral-800: 31, 42, 96; /* HEADING*/
  --color-neutral-900: 31, 42, 96; /* HEADING */

  --color-primary-500: 133, 205, 211; /* UNDERSCORE */

  --color-primary-700: 31, 42, 96; /* LINK */
```

**Comment by matthewolckers** [comment]
Made first attempt in updating colours in commit cda0084b6c8be9165ef31478b531a8316a354a2e , but now the colours of the dark mode of the site are messed up. Need to figure out how those are used.

**Comment by sandroradovanovic** [comment]
Edits were made in `assets/css/schemes/eaamo.css`. For everything I figured out, I made a comment in the file what is changing with each element.

Changes are visible with [7e1bf1f](https://github.com/EAAMO/conference24/commit/7e1bf1f00afaf12f2cfd089d69234e0ee585987e)

> One solution is we could turn off the dark version but that seems like a last resort.

To do this, one should go to `config/_default/params.toml`, set `defaultAppearance = "light"` and `autoSwitchAppearance = false`
