### ISSUE TITLE
Bring in some imagery on the call for participation page

### ISSUE THREAD

**Issue by matthewolckers** [EAAMO/conference2024#5]
On the [Call for Participation page](conference24/blob/main/content/cfp/index.md), Sam suggested:

> bring in some imagery to break this page up as it's very information heavy.

Perhaps there could be an illustration above or below each section header. I will ask Sam for some suggestions.

**Comment by sandroradovanovic** [comment]
Here is my proposition [6c25d4d](https://github.com/EAAMO/conference24/commit/6c25d4d23698a1eab0477d264874b18ef9d60772)
