### ISSUE TITLE
Move table of contents to left hand side

### ISSUE THREAD

**Issue by matthewolckers** [EAAMO/conference2024#6]
Sam comment on article table of contents
> I'm not overly sold on the use of this form of navigation to get to different points of info on the page, but I think it is helpful for someone to see at a glance what the information is broken down to. Would it be possible to see this on the left hand side of the main body of text, as I feel like it gets a little lost in order of priority/understanding being on the right. 

<img width="935" alt="image" src="https://github.com/EAAMO/conference24/assets/10639770/7e2d7121-3242-460c-b23b-b87f5ed266ff">

We need to check how complex this would be and if it creates other problems.

**Comment by sandroradovanovic** [comment]
The answer is in `layouts/_default/list.html` (line 17) and `layouts/_default/single.html` (line 38) files where we need to remove `lg:order-last` in the class of the HTML element. I had to adjust those files and add them to our project. In addition, I had to adjust the CSS and added .ps-5 selector in custom.css 

Closed with commit [#326555b](https://github.com/EAAMO/conference24/commit/326555bf7d87ce8c2b663857ca77376063783112)
