### ISSUE TITLE
Add the rest of the profile images on committee page and turn into shortcode

### ISSUE THREAD

**Issue by matthewolckers** [EAAMO/conference2024#9]
We still need to add profile images for the Executive Committee on the Committee page. 

Also, so we don't repeat code unnecessary, could we turn this into a shortcode?

See existing shortcodes in the theme [here](https://jpanther.github.io/congo/docs/shortcodes/) and then [here](https://gohugo.io/content-management/shortcodes/) is more details about Hugo shortcodes.

**Comment by matthewolckers** [comment]
Also, the grid might work better with Tailwind / Flexbox. The current code makes the profile images really small on mobile view.

**Comment by sandroradovanovic** [comment]
I used custom CSS to observe the page width.
